---
server:
  port : 8081
  servlet:
    context-path: /borris

spring:
  profiles : app1
  application:
    #服务模块名称，相同的名字的client被默认为同一个集群
    name : test-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/borrisdb?characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: borris
    password: Z7rfxRVrHnCQGLNVsK+JspGBPSmLMW0TP44FQaKtMREWCwjfAEQx87nfmrt1lOcyBVCOafmHAZ0uf5tB8H4AmA==
    type: com.alibaba.druid.pool.DruidDataSource
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOJe8Pnx6yqhdmrUpWw/K1roNAsNxiqqqAd+mtcDowPWQ9DHKmZ1fl2BMe5PbVFNneDxkkM0AUV/pfTRBihliocCAwEAAQ==
    druid:
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publickey};
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # config用于使connection-properties这个参数生效，暂时只发现它可以用于加密
      filters: config,stat,wall,log4j
      use-global-data-source-stat: true
      filter:
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: borris
        login-password: 1234
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

mybatis:
  mapper-locations: classpath:persist/*.xml

eureka:
  client:
    #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
    registry-fetch-interval-seconds : 5
    service-url:
      defaultZone : http://borris:sctiy@localhost:7001/eureka/,http://borris:sctiy@localhost:7002/eureka/,http://borris:sctiy@localhost:7003/eureka/
  instance:
    #心跳间隔
    lease-renewal-interval-in-seconds : 5
    #心跳停止后的节点过期时间
    lease-expiration-duration-in-seconds : 10
    instance-id : localhost:${server.port}

---
server:
  port : 8082
  servlet:
    context-path: /borris

spring:
  profiles: app2
  application:
    #服务模块名称，相同的名字的client被默认为同一个集群
    name : test-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/borrisdb?characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: borris
    password: Z7rfxRVrHnCQGLNVsK+JspGBPSmLMW0TP44FQaKtMREWCwjfAEQx87nfmrt1lOcyBVCOafmHAZ0uf5tB8H4AmA==
    type: com.alibaba.druid.pool.DruidDataSource
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOJe8Pnx6yqhdmrUpWw/K1roNAsNxiqqqAd+mtcDowPWQ9DHKmZ1fl2BMe5PbVFNneDxkkM0AUV/pfTRBihliocCAwEAAQ==
    druid:
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publickey};
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,stat,wall,log4j
      use-global-data-source-stat: true
      filter:
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: borris
        login-password: 1234
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

mybatis:
  mapper-locations: classpath:persist/*.xml

eureka:
  client:
    #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
    registry-fetch-interval-seconds : 5
    service-url:
      defaultZone : http://borris:sctiy@localhost:7001/eureka/,http://borris:sctiy@localhost:7002/eureka/,http://borris:sctiy@localhost:7003/eureka/
  instance:
    #心跳间隔
    lease-renewal-interval-in-seconds : 5
    #心跳停止后的节点过期时间
    lease-expiration-duration-in-seconds : 10
    instance-id : localhost:${server.port}
